# Official documentation: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

# send an alert when a deployment fails
alerts:
- rule: DEPLOYMENT_FAILED
# hook up a domain in digitalocean dashboard > networking > domains
# so that you can use it here
# domains:
# - domain: example-app.com
#   type: PRIMARY
# features:
# - enable-kata-build


# the name of the overall app. remember that an app in digital ocean app-platform
# can include many services
name: example-app-name
region: nyc
services:
# cors security, for when you are deploying a backend app and want to only
# allow a certain frontend domain to access your web service.
# - cors:
#     allow_origins:
#     - prefix: https://internal.example-app.com

# if you are using docker to deploy, set the path from the root of the
# repository that you have connected
  dockerfile_path: Dockerfile
# an obvious one, any environment variables.
  envs:
  - key: HUGO_VERSION
    # this option is used if the build process should have access to variables
    scope: RUN_AND_BUILD_TIME
    value: 0.81.0
# the repository that you want this app to deploy on. make sure you have
# enabled permissions for this repo in digital ocean dashboard
  github:
    branch: main
    deploy_on_push: true
    # <your github username>/<repo name>
    repo: example-org/example-repo
  http_port: 80
  instance_count: 2
  instance_size_slug: professional-xs
  name: example-service-name
  routes:
  - path: /


